mainList = {
    'Бендеры': 'https://www.gismeteo.md/weather-bender-11294/',
    'Григориополь': 'https://www.gismeteo.md/weather-grigoriopol-14470/',
    'Днестровск': 'https://www.gismeteo.md/weather-dnestrovsc-14469/',
    'Дубоссары': 'https://www.gismeteo.md/weather-dubasari-14473/',
    'Каменка': 'https://www.gismeteo.md/weather-camenca-14478/',
    'Рыбница': 'https://www.gismeteo.md/weather-ribnita-4977/',
    'Слободзея': 'https://www.gismeteo.md/weather-slobozia-46999/',
    'Тирасполь': 'https://www.gismeteo.md/weather-tiraspol-4981/'
}

fullList = {
    'Бендеры': 'https://www.gismeteo.md/weather-bender-11294/',
    'Ближний хутор': 'https://www.gismeteo.md/weather-blijnii-hutor-70976/',
    'Броштяны': 'https://www.gismeteo.md/weather-brosteni-46966/',
    'Бутор': 'https://www.gismeteo.md/weather-butor-70992/',
    'Бутучаны': 'https://www.gismeteo.md/weather-butuceni-46967/',
    'Бычок': 'https://www.gismeteo.md/weather-bicioc-70990/',
    'Валя-Адынка': 'https://www.gismeteo.md/weather-valea-adinca-46968/',
    'Владимировка': 'https://www.gismeteo.md/weather-vladimirovca-46969/',
    'Выхватинцы': 'https://www.gismeteo.md/weather-vikhvatinets-46970/',
    'Гидирим': 'https://www.gismeteo.md/weather-ghidirim-46971/',
    'Гиска': 'https://www.gismeteo.md/weather-gisca-46972/',
    'Глиное': 'https://www.gismeteo.md/weather-hlinaia-46973/',
    'Григориополь': 'https://www.gismeteo.md/weather-grigoriopol-14470/',
    'Грушка': 'https://www.gismeteo.md/weather-hrusca-46974/',
    'Далакэу': 'https://www.gismeteo.md/weather-delacau-46998/',
    'Днестровск': 'https://www.gismeteo.md/weather-dnestrovsc-14469/',
    'Дубоссары': 'https://www.gismeteo.md/weather-dubasari-14473/',
    'Ержово': 'https://www.gismeteo.md/weather-hirjau-70993/',
    'Каменка': 'https://www.gismeteo.md/weather-camenca-14478/',
    'Карагаш': 'https://www.gismeteo.md/weather-caragas-70983/',
    'Карманово': 'https://www.gismeteo.md/weather-carmanova-46975/',
    'Катериновка': 'https://www.gismeteo.md/weather-caterinovca-46976/',
    'Кицканы': 'https://www.gismeteo.md/weather-chitcani-46977/',
    'Колбасна': 'https://www.gismeteo.md/weather-cobasna-70980/',
    'Колосово': 'https://www.gismeteo.md/weather-colosova-46997/',
    'Копанка': 'https://www.gismeteo.md/weather-copanca-46978/',
    'Коржево': 'https://www.gismeteo.md/weather-corjova-46979/',
    'Коротное': 'https://www.gismeteo.md/weather-corotna-70984/',
    'Красная Горка': 'https://www.gismeteo.md/weather-crasnaia-gorca-46996/',
    'Красненькое': 'https://www.gismeteo.md/weather-krasnenkoe-70979/',
    'Красногорка': 'https://www.gismeteo.md/weather-krasnogorka-70991/',
    'Красное': 'https://www.gismeteo.md/weather-crasnoe-46980/',
    'Кременчуг': 'https://www.gismeteo.md/weather-cremenciug-70987/',
    'Лунга': 'https://www.gismeteo.md/weather-lunga-46981/',
    'Малаешты': 'https://www.gismeteo.md/weather-malaiesti-46995/',
    'Маяк': 'https://www.gismeteo.md/weather-maiac-46982/',
    'Меренешты': 'https://www.gismeteo.md/weather-merenesti-46983/',
    'Мокра': 'https://www.gismeteo.md/weather-mokra-70978/',
    'Незавертайловка': 'https://www.gismeteo.md/weather-nezavertaylovka-70985/',
    'Окница': 'https://www.gismeteo.md/weather-ocnita-70988/',
    'Парканы': 'https://www.gismeteo.md/weather-parcani-46984/',
    'Первомайск': 'https://www.gismeteo.md/weather-pervomaisc-46985/',
    'Плоть': 'https://www.gismeteo.md/weather-plot-46986/',
    'Подойма': 'https://www.gismeteo.md/weather-podoima-46987/',
    'Попенки': 'https://www.gismeteo.md/weather-popencu-70977/',
    'Рашково': 'https://www.gismeteo.md/weather-rascov-46988/',
    'Рыбница ': 'https://www.gismeteo.md/weather-ribnita-4977/',
    'Слободзея': 'https://www.gismeteo.md/weather-slobozia-46999/',
    'Спея': 'https://www.gismeteo.md/weather-speya-70981/',
    'Суклея': 'https://www.gismeteo.md/weather-sucleia-46989/',
    'Ташлык': 'https://www.gismeteo.md/weather-taslic-46990/',
    'Терновка': 'https://www.gismeteo.md/weather-tirnauca-46991/',
    'Тея': 'https://www.gismeteo.md/weather-teya-70982/',
    'Тирасполь': 'https://www.gismeteo.md/weather-tiraspol-4981/',
    'Ульма': 'https://www.gismeteo.md/weather-ulma-70989/',
    'Фрунзе': 'https://www.gismeteo.md/weather-frunza-70986/',
    'Хрустовая': 'https://www.gismeteo.md/weather-hristovaia-46992/',
    'Чобручи': 'https://www.gismeteo.md/weather-cioburciu-46993/',
    'Шипка': 'https://www.gismeteo.md/weather-sipca-46994/'
}
module.exports = {
    mainList,
    fullList,
}

